import { FC, ReactElement } from "react"
import { Logo, Paragraph } from "../index"

const Footer: FC = (): ReactElement => (
    <div className="footer-block">
        <hr/>
        <Logo size="large"/>
        <Paragraph size="medium" color="ghost">
            Discover through a collection of imaginative and visually stunning images generated by Pointer
        </Paragraph>
        <div className="author-block">
            <small>Site developed by: <br/> Maksym Sverlovych | msverlovych@gmail.com</small>
        </div>
    </div>
)

export default Footer